### PR TITLE
🔨 Fix missing Sentry params for build

### PR DESCRIPTION
**Pull request by nwingt**
Set required config in .env and override with `SENTRY_LOAD_DOTENV=0`, allowing CI to read config from `sentry.properties`

### CODE REVIEW

**Review by shellyYG — APPROVED** [review]

**Comment by williamchong** [comment]
Where should SENTRY_LOAD_DOTENV=0 be set or is it set now?

**Comment by nwingt** [comment]
Set in secrets

**Comment by nwingt** [comment]
Or do u want to set it in GitHub workflow config?

**Comment by williamchong** [comment]
> Or do u want to set it in GitHub workflow config?
Setting in workflow config seems more verbose, and it is not really secret

**Comment by nwingt** [comment]
@williamchong Updated

**Review by williamchong — APPROVED** [review]

**Pull request merged**
