### PR TITLE
🥅 Prevent 0 gas

### PR DESCRIPTION
**Pull request by nwingt**

### CODE REVIEW

**Comment by williamchong** [comment]
Should we add some console.warn and collect some statistics via sentry to see how often it happens?

**Comment by nwingt** [comment]
It is already captured by Sentry in L159

**Comment by williamchong** [comment]
I mean logs for how often `estimatedGas === 0` happens, sorry for confusion
Does L159 catch this case?

**Review by nnkken — APPROVED** [review]

**Review by williamchong — CHANGES_REQUESTED** [review]
Where is `logMessage` used?

**Comment by nwingt** [comment]
Force-pushed

**Review by williamchong — APPROVED** [review]

**Pull request merged**
