### PR TITLE
🐛 Show `< 0.0001` when reward amount is too small

### PR DESCRIPTION
**Pull request by williamchong**

### CODE REVIEW

**Review by nwingt — COMMENTED** [review]
Can simply format in `calcSumOfContentProps()` ?
https://github.com/likecoin/likecoin-app/blob/eeb46e9a148ac0e82e28de0cf79fbb0970da80fe/app/models/statistics-store/statistics-rewarded-week.ts#L35-L74

**Comment by williamchong** [comment]
`calcSumOfContentProps` currently returns number, but the formatted result is string. Would I have to change the interfaces of all the `.create()` that used these views?

**Comment by williamchong** [comment]
Just found out I accidentally pushed to origin, just fixed

**Comment by nwingt** [comment]
Why I don't see any committed changes?

**Comment by williamchong** [comment]
> Why I don't see any committed changes?

Because I haven't change anything yet. Do you think I should change all ui's create() that use this number to use `string` instead of `number` as param?

**Comment by nwingt** [comment]
I think that's ok, no need to change

**Pull request merged**
